# Generated by Django 4.0.4 on 2022-04-12 20:36

from django.db import migrations, models
import django.db.models.deletion
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_description_alter_blog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=100, null=sqlalchemy.sql.expression.false),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=sqlalchemy.sql.expression.false)),
                ('comment', models.CharField(max_length=500, null=sqlalchemy.sql.expression.false)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('id_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blog')),
            ],
        ),
    ]
